---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kad
  labels:
    app: kad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kad
  template:
    metadata:
      labels:
        app: kad
    spec:
      containers:
      - name: kad
        image: prgcont/kad
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: kad
  annotations:
    prometheus.io/scrape: "true"
spec:
  selector:
    app: kad
  ports:
    - protocol: TCP
      targetPort: 5000
      port: 80

